apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../namespace.yaml
  - ../../configmap.yaml
  - ../../pvc.yaml
  - ../../deployment.yaml
  - ../../service.yaml
  - ../../pdb.yaml
  - ../../networkpolicy.yaml
  - ../../agent-deployment.yaml
  - serviceaccount.yaml
patches:
  - path: pvc-storageclass.yaml
  - path: workload-identity.yaml
