apiVersion: v1
kind: ServiceAccount
metadata:
  name: kronos-control-plane
  namespace: kronos
  annotations:
    iam.gke.io/gcp-service-account: kronos-control-plane@example-project.iam.gserviceaccount.com
