apiVersion: apps/v1
kind: Deployment
metadata:
  name: kronos-control-plane
  namespace: kronos
spec:
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: kronos-control-plane
