apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kronos-control-plane-ingress
  namespace: kronos
  labels:
    app.kubernetes.io/name: kronos
    app.kubernetes.io/component: control-plane
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: kronos
      app.kubernetes.io/component: control-plane
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: kronos
      ports:
        - protocol: TCP
          port: 8500
